### ISSUE TITLE
Multiplication overflow in lookup_compound for strings with more than 18 characters without spaces

### ISSUE THREAD

**Issue by sam-qordoba** [reneklacan/symspell#17]
Code to reproduce:

`/src/main.rs`
```rust
extern crate symspell;

use symspell::{AsciiStringStrategy, SymSpell};

fn main() {
    let mut symspell: SymSpell<AsciiStringStrategy> = SymSpell::default();

    symspell.load_dictionary("data/frequency_dictionary_en_82_765.txt", 0, 1, " ");
    symspell.load_bigram_dictionary(
      "./data/frequency_bigramdictionary_en_243_342.txt",
      0,
      2,
      " "
    );


    let sentence = "heymasdaasdnasdhfdgotuyjkwareyou";
    let compound_suggestions = symspell.lookup_compound(sentence, 2);
    println!("this causes a panic from multiplication overflow:");
    println!("{:?}", compound_suggestions);
}
```

`Cargo.toml`
```toml
[package]
name = "symspell_overflow_test"
version = "0.0.1"
authors = ["Your name <you@example.com>"]

[dependencies]
symspell = "0.4.0"

```

`cargo build && cargo run`

ends with:

```sh
     Running `target/debug/symspell_overflow_test`
thread 'main' panicked at 'attempt to multiply with overflow', /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/num/mod.rs:1938:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So then I ran `RUST_BACKTRACE=full cargo run` and got

```sh
$ RUST_BACKTRACE=full cargo run
   Compiling symspell_overflow_test v0.0.1 (/Users/sh/q/scratch/rust_symspell)
    Finished dev [unoptimized + debuginfo] target(s) in 3.85s
     Running `target/debug/symspell_overflow_test`
thread 'main' panicked at 'attempt to multiply with overflow', /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/num/mod.rs:1938:28
stack backtrace:
   0:        0x10fdcacff - backtrace::backtrace::libunwind::trace::he11f30ca242db87a
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:        0x10fdcacff - backtrace::backtrace::trace_unsynchronized::h94ee7e02d675d126
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:        0x10fdcacff - std::sys_common::backtrace::_print_fmt::h37608594d2ca99cd
                               at src/libstd/sys_common/backtrace.rs:78
   3:        0x10fdcacff - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h248f4d24421ce424
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x10fde2d0e - core::fmt::write::h71c869ef05998146
                               at src/libcore/fmt/mod.rs:1069
   5:        0x10fdc9407 - std::io::Write::write_fmt::h6c18aa5d536af338
                               at src/libstd/io/mod.rs:1427
   6:        0x10fdccaca - std::sys_common::backtrace::_print::h9c7302dcb6bc9d80
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x10fdccaca - std::sys_common::backtrace::print::hef121cec42b01afc
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x10fdccaca - std::panicking::default_hook::{{closure}}::h718f6688c2c8071f
                               at src/libstd/panicking.rs:198
   9:        0x10fdcc80c - std::panicking::default_hook::h559165f971f7c4f9
                               at src/libstd/panicking.rs:218
  10:        0x10fdcd038 - std::panicking::rust_panic_with_hook::h58f6a2672cadd86f
                               at src/libstd/panicking.rs:511
  11:        0x10fdccc02 - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:        0x10fde834f - core::panicking::panic_fmt::h599bb93f00742409
                               at src/libcore/panicking.rs:111
  13:        0x10fde82a7 - core::panicking::panic::hbb1c51e4345889f0
                               at src/libcore/panicking.rs:54
  14:        0x10fd8e960 - core::num::<impl i64>::pow::h49983a2eaaa29165
                               at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/num/mod.rs:1938
  15:        0x10fda7564 - symspell::symspell::SymSpell<T>::lookup_compound::h77e9a357a7b349df
                               at /Users/sh/.cargo/registry/src/github.com-1ecc6299db9ec823/symspell-0.4.0/src/symspell.rs:615
  16:        0x10fd9848c - symspell_overflow_test::main::h4a6f249518fcfc2f
                               at src/main.rs:18
  17:        0x10fd8c12e - std::rt::lang_start::{{closure}}::h1d323437a9a0069f
                               at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/rt.rs:67
  18:        0x10fdcd414 - std::rt::lang_start_internal::{{closure}}::h9e16343c6c2438e4
                               at src/libstd/rt.rs:52
  19:        0x10fdcd414 - std::panicking::try::do_call::h3e909382cd5fe48d
                               at src/libstd/panicking.rs:331
  20:        0x10fdcd414 - std::panicking::try::ha497cd00ed772379
                               at src/libstd/panicking.rs:274
  21:        0x10fdcd414 - std::panic::catch_unwind::h798c76fd47e59915
                               at src/libstd/panic.rs:394
  22:        0x10fdcd414 - std::rt::lang_start_internal::h70084482207aef9f
                               at src/libstd/rt.rs:51
  23:        0x10fd8c111 - std::rt::lang_start::h1483ded7753c42a1
                               at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/rt.rs:67
  24:        0x10fd985c2 - symspell_overflow_test::main::h4a6f249518fcfc2f
```

So the error is [on this line](https://github.com/reneklacan/symspell/blob/master/src/symspell.rs#L615),

```rust
let si_count: f64 = 10f64
    / ((10i64).pow(self.string_strategy.len(&term_list1[i]) as u32)) as f64;
```

**Comment by sam-qordoba** [comment]
I think the fix is to use `saturating_pow`, [docs](https://doc.rust-lang.org/std/primitive.u32.html#method.saturating_pow), I will report back

**Comment by sam-qordoba** [comment]
BTW I know absolutely nothing about Rust, so, sorry if this is stupid.

`saturating_pow` does not fix the issue.

**Comment by sam-qordoba** [comment]
Update: `saturating_pow` DOES fix the error, it just showed up in two places. Will open a PR with a test for this and this "fix".

This is more of a hack than a fix though, I think a real fix would involve using something like [Rug](https://crates.io/crates/rug) to actually allow these numbers to be as big/small as they are.
